Add undo functionality for delete
AY2324S1-CS2103T-W09-1/tp pull request #53
Opened 2023-10-15 09:44 UTC by glenngnng

Currently, the delete feature is complete and there are no further changes needed for delete. Furthermore, the clear feature (which essentially deletes all) has been implemented. Hence, an undo functionality will be a nice addition to delete. This saves the user time as the user does not need to manually re-type an add function for the deleted person.

Undo will undo the most recent delete performed by the user. Undo can only be performed once and after a delete. If 2 deletes are performed in a row, only the most recent delete can be undone.

Possible increments: Undo for the adding of a person, but this is essentially delete.

2023-10-15 15:15 UTC, glenngnng commented
CodeCov checks have passed!

2023-10-16 12:51 UTC, limzhenwy requested changes
LGTM. Just possibly a nit to fix.

2023-10-16 12:51 UTC, limzhenwy commented on src/main/java/seedu/address/logic/commands/UndoCommand.java
> +    public static final String MESSAGE_UNDO_SUCCESS = "Undo Successful!";
minor nitpick, seeing as how all other texts do not capitalize each starting letter, maybe this could be changed to follow the format?

2023-10-16 12:51 UTC, limzhenwy commented on src/main/java/seedu/address/logic/commands/UndoCommand.java
> +    public static final String MESSAGE_UNDO_SUCCESS = "Undo Successful!";
```suggestion
    public static final String MESSAGE_UNDO_SUCCESS = "Undo successful!";
```

2023-10-16 12:51 UTC, merged